parameters:
#    ue235_bibliotheque.example.class: UE235\BibliothequeBundle\Example
    cover_directory: './public/images/covers/'

services:
#    ue235_bibliotheque.example:
#        class: %ue235_bibliotheque.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
